### PR TITLE
Create PVC in the bpm reconciler again

### PR DESCRIPTION
**Pull request by aduffeck**
This reverts part of 573238c and f33124f. Without this code there are
dangling PVC references in the qsts pods.

### CODE REVIEW

**Comment by phil9909** [comment]
Are you sure we need this?
I changed it, because it did not work when scaling. With my change the creation of `PVC`s is delegated to the `ExtendedStatefulSet`-Controller, which will create a `PVC` for every replica and the `PodMutator` updates the `Pod` spec to reference the correct `PVC`.

**Comment by aduffeck** [comment]
When trying to deploy kubecf on kind locally I ran into the problem that the PVCs were not being created. Bringing back this code fixed the problem for me.
Maybe there's something missing to make the new approach work in all cases? Can you point me to the code that's creating the PVCs for you?

**Comment by phil9909** [comment]
Relevant code:

https://github.com/cloudfoundry-incubator/cf-operator/blob/bc3bd206d885765f9f09aba53b2d510edb8f57a9/pkg/kube/controllers/quarksstatefulset/quarksstatefulset_reconciler.go#L122-L128

Relevant documentation: 
https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/controllers/quarks_statefulset.md#volume-management

I have never tested it with a `kind` cluster.
Do you see any Pods or StatefulSets containing `volume-management` in their name?

**Comment by f0rmiga** [comment]
@aduffeck Is it possible that you hit a bug that I fixed here? https://github.com/SUSE/kubecf/pull/166
It was introduced a few hours earlier yesterday here https://github.com/SUSE/kubecf/pull/153.

**Comment by aduffeck** [comment]
@f0rmiga no, SUSE/kubecf#153 is not part of my branch. After talking to @phil9909 it looks like the pod mutating webhook that's supposed to configure the proper pvc isn't working as expected in my case. I'll continue looking into it tomorrow.

**Comment by aduffeck** [comment]
For whatever reason I can not reproduce the issue that made this change necessary anymore with a fresh kind cluster. I'll retract the pr and assume it was a local issue for now.

**Pull request closed without merging**
