### PR TITLE
Fix linter error

### PR DESCRIPTION
**Pull request by aduffeck**

### CODE REVIEW

**Comment by jandubois** [comment]
I would merge, but CI shows an error (that is obviously not caused by this PR):

```
pkg/kube/controllers/extendedjob/pod_state.go:9:2: unknown import path "k8s.io/kubernetes/pkg/api/v1/pod": cannot find module providing package k8s.io/kubernetes/pkg/api/v1/pod
```

**Comment by manno** [comment]
@jandubois I think that's an unrelated go mod download issue with the big (127mb) kubernetes package: https://www.pivotaltracker.com/story/show/164240755

**Comment by jandubois** [comment]
> I think that's an unrelated go mod download issue

Absolutely; that's why I said: "obviously not caused by this PR". But Github didn't give me a merge button with failing CI; so how did you get this merged? Did @viovanov disable the required check again?

**Comment by jandubois** [comment]
> so how did you get this merged?

Nevermind, I see now that you merged `master` into this PR, which made CI succeed. Somehow I missed this before.

**Pull request merged**
